#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_GrenadeLauncher_ShockWave_Athena

#include "Basic.hpp"

#include "B_Ranged_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_GrenadeLauncher_ShockWave_Athena.B_GrenadeLauncher_ShockWave_Athena_C
// 0x0010 (0x1280 - 0x1270)
class AB_GrenadeLauncher_ShockWave_Athena_C final : public AB_Ranged_Generic_C
{
public:
	class UStaticMeshComponent*                   Reload_MagazineReload;                             // 0x1270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Reload_Ammo;                                       // 0x1278(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_GrenadeLauncher_ShockWave_Athena_C">();
	}
	static class AB_GrenadeLauncher_ShockWave_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_GrenadeLauncher_ShockWave_Athena_C>();
	}
};

}

