#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP13_Sandcastle_Mannequin

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP13_Sandcastle_Mannequin.BP13_Sandcastle_Mannequin_C
// 0x0010 (0x04A8 - 0x0498)
class ABP13_Sandcastle_Mannequin_C final : public AFortPlayerMannequin
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0498(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 Sandcastle_Male;                                   // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP13_Sandcastle_Mannequin(int32 EntryPoint);
	void OnPartChanged(const class UCustomCharacterPart* OldPart, const class UCustomCharacterPart* NewPart, EFortCustomPartType PartType);
	void ReceiveBeginPlay();
	void OnVariantChanged(const struct FGameplayTag& VariantChannel, const struct FGameplayTag& OldVariantTag, const struct FGameplayTag& NewVariantTag);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP13_Sandcastle_Mannequin_C">();
	}
	static class ABP13_Sandcastle_Mannequin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP13_Sandcastle_Mannequin_C>();
	}
};

}

