#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: DA_BoostJumpPack

#include "Basic.hpp"

#include "CommonInput_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DA_BoostJumpPack.DA_BoostJumpPack_C
// 0x0068 (0x0D08 - 0x0CA0)
class ADA_BoostJumpPack_C final : public AFortCustomizableAbilityDecoTool
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0CA0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTagContainer                  ErrorReason;                                       // 0x0CA8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTagContainer                  ErrorReasonGamepad;                                // 0x0CC8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTagContainer                  ErrorCannotUse;                                    // 0x0CE8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_DA_BoostJumpPack(int32 EntryPoint);
	void BPPressTrigger(class AFortDecoHelper* FortDecoHelper);
	void RaiseUsageError(const struct FGameplayTagContainer& FailedReason);
	void IsOnGround(bool* bOnGround);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DA_BoostJumpPack_C">();
	}
	static class ADA_BoostJumpPack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADA_BoostJumpPack_C>();
	}
};

}

