#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_FringePlank_PassiveFromEvent_Athena

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_FringePlank_PassiveFromEvent_Athena.GA_FringePlank_PassiveFromEvent_Athena_C
// 0x0020 (0x0A98 - 0x0A78)
class UGA_FringePlank_PassiveFromEvent_Athena_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A78(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AB_FringePlank_Generic_Athena_C*        Weapon;                                            // 0x0A80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        FortPawn;                                          // 0x0A88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             OutOfChargesSound;                                 // 0x0A90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_FringePlank_PassiveFromEvent_Athena(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void OnCompleted_4979E8004A3CAF88A4C44F903E62D3DC(const struct FGameplayTag& NotifyTag);
	void OnBlendOut_4979E8004A3CAF88A4C44F903E62D3DC(const struct FGameplayTag& NotifyTag);
	void OnInterrupted_4979E8004A3CAF88A4C44F903E62D3DC(const struct FGameplayTag& NotifyTag);
	void OnCancelled_4979E8004A3CAF88A4C44F903E62D3DC(const struct FGameplayTag& NotifyTag);
	void OnNotifyBegin_4979E8004A3CAF88A4C44F903E62D3DC(const struct FGameplayTag& NotifyTag);
	void OnNotifyEnd_4979E8004A3CAF88A4C44F903E62D3DC(const struct FGameplayTag& NotifyTag);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_FringePlank_PassiveFromEvent_Athena_C">();
	}
	static class UGA_FringePlank_PassiveFromEvent_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_FringePlank_PassiveFromEvent_Athena_C>();
	}
};

}

