#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ItemInfoPresentationWidget

#include "Basic.hpp"

#include "ItemInfoPresentationWidget_classes.hpp"
#include "ItemInfoPresentationWidget_parameters.hpp"


namespace SDK
{

// Function ItemInfoPresentationWidget.ItemInfoPresentationWidget_C.HandleIntro
// (Public, BlueprintCallable, BlueprintEvent)

void UItemInfoPresentationWidget_C::HandleIntro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemInfoPresentationWidget_C", "HandleIntro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ItemInfoPresentationWidget.ItemInfoPresentationWidget_C.HandleInitialState
// (Public, BlueprintCallable, BlueprintEvent)

void UItemInfoPresentationWidget_C::HandleInitialState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemInfoPresentationWidget_C", "HandleInitialState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ItemInfoPresentationWidget.ItemInfoPresentationWidget_C.HandleOutro
// (Public, BlueprintCallable, BlueprintEvent)

void UItemInfoPresentationWidget_C::HandleOutro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemInfoPresentationWidget_C", "HandleOutro");

	UObject::ProcessEvent(Func, nullptr);
}

}

