#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ItemPresentationGenericRewardHeader

#include "Basic.hpp"


namespace SDK::Params
{

// Function ItemPresentationGenericRewardHeader.ItemPresentationGenericRewardHeader_C.HandleIntro
// 0x0008 (0x0008 - 0x0000)
struct ItemPresentationGenericRewardHeader_C_HandleIntro final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function ItemPresentationGenericRewardHeader.ItemPresentationGenericRewardHeader_C.HandleInitialState
// 0x0008 (0x0008 - 0x0000)
struct ItemPresentationGenericRewardHeader_C_HandleInitialState final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationTimeRange_ReturnValue;       // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function ItemPresentationGenericRewardHeader.ItemPresentationGenericRewardHeader_C.HandleOutro
// 0x0008 (0x0008 - 0x0000)
struct ItemPresentationGenericRewardHeader_C_HandleOutro final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

