#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MangDataTrackerV2

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MangDataTrackerV2.MangDataTrackerV2_C
// 0x0000 (0x01A8 - 0x01A8)
class UMangDataTrackerV2_C final : public UFortGameplayDataTrackerComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MangDataTrackerV2_C">();
	}
	static class UMangDataTrackerV2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMangDataTrackerV2_C>();
	}
};

}

