#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: NPC_Pawn_Wildlife_Parent

#include "Basic.hpp"

#include "NPC_Pawn_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPC_Pawn_Wildlife_Parent.NPC_Pawn_Wildlife_Parent_C
// 0x0000 (0x2550 - 0x2550)
class ANPC_Pawn_Wildlife_Parent_C final : public ANPC_Pawn_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NPC_Pawn_Wildlife_Parent_C">();
	}
	static class ANPC_Pawn_Wildlife_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPC_Pawn_Wildlife_Parent_C>();
	}
};

}

