#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SR_Core

#include "Basic.hpp"

#include "SrirachaRanch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SR_Core.SR_Core_C
// 0x0000 (0x0288 - 0x0288)
class USR_Core_C final : public UStreamingRadioPlayerComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SR_Core_C">();
	}
	static class USR_Core_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USR_Core_C>();
	}
};

}

