#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ValetUI

#include "Basic.hpp"


namespace SDK
{

// Enum ValetUI.EFuelTankState
// NumValues: 0x0004
enum class EFuelTankState : uint8
{
	Empty                                    = 0,
	LowFuel                                  = 1,
	RegularFuel                              = 2,
	EFuelTankState_MAX                       = 3,
};

}

